#!/bin/bash

if [ "$(command -v python3)" ]; then
    python_version=$(python3 --version 2>&1 | awk '{print $2}')
    if [[ "$(printf '%s\n' "3.10" "$python_version" | sort -V | head -n1)" == "3.10" ]]; then
        echo -e "[\x1b[1;32mOK\x1b[0m] Found python \x1b[1;33m3.10\x1b[0m or later"
        echo -e "     Used version = \x1b[1;33m$python_version\x1b[0m\n"
    else
        echo "[\x1b[1;31mERROR\x1b[0m] Python \x1b[1;33m3.10\x1b[0m or later is required"
        echo "        Installed version = \x1b[1;31m$python_version\x1b[0m"
        exit 1
    fi
else
    echo "ERROR: python3 not found"
    exit 1
fi

echo -e "----------------------------------------\n"

python3 unet/ "$@"
